[theme]
# Thème : Aston Martin F1 2026
primaryColor = "#00665F" # Vert Aston Martin officiel
backgroundColor = "#0A0F0D" # Noir profond / carbone
secondaryBackgroundColor = "#151B19" # Gris carbone plus clair
textColor = "#FFFFFF" # Texte blanc
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
